language: node_js

node_js:
  - "8"

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - $HOME/.nvm
    - $HOME/.npm

before_install:
  - yarn install:token

install:
  - yarn

script:
  - yarn build

deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: master

after_success:
  - npx semantic-release

notifications:
  email: false
